---
- name: Create SFTP folders
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ ssh_config_sftp_folders }}"
