---
- name: AuthorizedKeysCommand variables checks
  fail:
    msg="You must define AuthorizedKeysCommand variables"
  when: >
    ssh_config_authorized_keys_command|bool
    and ('%s'|format(ssh_config_sshauth_login)|length == 0
    or '%s'|format(ssh_config_sshauth_passwd)|length == 0
    or '%s'|format(ssh_config_sshauth_fqdn)|length == 0)

- name: Copy sshauth script
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "etc/ssh/sshauth.j2"
      dest: "/etc/ssh/sshauth"
      owner: "root"
      group: "root"
      mode: "0755"
    - src: "etc/ssh/sshauth.json.j2"
      dest: "/etc/ssh/sshauth.json"
      owner: "nobody"
      group: "nogroup"
      mode: "0400"

- name: Install required packages
  apt:
    name:
    - python3-requests
    state: "present"
